//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36403
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncClientInstaller.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyncClientResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncClientResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncClientInstaller.Resource.SyncClientResource", typeof(SyncClientResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Server Password.
        /// </summary>
        internal static string ADServerPassword {
            get {
                return ResourceManager.GetString("ADServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Server Username.
        /// </summary>
        internal static string ADServerUsername {
            get {
                return ResourceManager.GetString("ADServerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api key.
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid api key into the text box provided below. This api key will be used to connect to the cloudid and will be used for updating the user&apos;s metadata further into cloud..
        /// </summary>
        internal static string ApiKeyFrmDescription {
            get {
                return ResourceManager.GetString("ApiKeyFrmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter API Key.
        /// </summary>
        internal static string ApiKeyFrmHeading {
            get {
                return ResourceManager.GetString("ApiKeyFrmHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key cannot be empty. Please enter valid Api Key..
        /// </summary>
        internal static string ApiKeyValidationMsg {
            get {
                return ResourceManager.GetString("ApiKeyValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the base api url for the key &apos;ApiBaseUrl&apos; in the configuration file.
        /// </summary>
        internal static string ApiUrlValidationMsg {
            get {
                return ResourceManager.GetString("ApiUrlValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string AuthenticationValidationMsg {
            get {
                return ResourceManager.GetString("AuthenticationValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseCaption {
            get {
                return ResourceManager.GetString("CloseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit installation?.
        /// </summary>
        internal static string ClosingText {
            get {
                return ResourceManager.GetString("ClosingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string CommonChangeLanguage {
            get {
                return ResourceManager.GetString("CommonChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string CommonConfirmation {
            get {
                return ResourceManager.GetString("CommonConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string CommonEnglish {
            get {
                return ResourceManager.GetString("CommonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string CommonFinish {
            get {
                return ResourceManager.GetString("CommonFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string CommonInstall {
            get {
                return ResourceManager.GetString("CommonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string CommonNext {
            get {
                return ResourceManager.GetString("CommonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norsk.
        /// </summary>
        internal static string CommonNorsk {
            get {
                return ResourceManager.GetString("CommonNorsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string CommonPrevious {
            get {
                return ResourceManager.GetString("CommonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either customer short code or api key is invalid. Please enter the valid customer short code and api key to proceed further..
        /// </summary>
        internal static string CustomerApiKeyValidation {
            get {
                return ResourceManager.GetString("CustomerApiKeyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code.
        /// </summary>
        internal static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Email.
        /// </summary>
        internal static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address. This Email address is used to send the notification mails..
        /// </summary>
        internal static string CustomerEmailDescription {
            get {
                return ResourceManager.GetString("CustomerEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address cannot be blank.
        /// </summary>
        internal static string CustomerEmailRequired {
            get {
                return ResourceManager.GetString("CustomerEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string CustomerEmailValidation {
            get {
                return ResourceManager.GetString("CustomerEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid customer name in the text box provided below. This customer will be validated against the api method. This customer short code is used to update the user&apos;s metadata into the cloud for this customer..
        /// </summary>
        internal static string CustomerFrmDescription {
            get {
                return ResourceManager.GetString("CustomerFrmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Customer Name.
        /// </summary>
        internal static string CustomerFrmHeading {
            get {
                return ResourceManager.GetString("CustomerFrmHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer short code.
        /// </summary>
        internal static string CustomerShortCode {
            get {
                return ResourceManager.GetString("CustomerShortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer short code cannot be empty. Please enter a valid customer short code.
        /// </summary>
        internal static string CustomerShortCodeValidationMsg {
            get {
                return ResourceManager.GetString("CustomerShortCodeValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Active Directory Server Name.
        /// </summary>
        internal static string EnableADServerText {
            get {
                return ResourceManager.GetString("EnableADServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Path.
        /// </summary>
        internal static string InstallationPath {
            get {
                return ResourceManager.GetString("InstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string InstallationPathFrmBrowse {
            get {
                return ResourceManager.GetString("InstallationPathFrmBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid path in the textbox below. This path will be used for installing and scheduling the job to run on regular basis and update the user metadata into cloud..
        /// </summary>
        internal static string InstallationPathFrmDescription {
            get {
                return ResourceManager.GetString("InstallationPathFrmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the installation path.
        /// </summary>
        internal static string InstallationPathFrmHeading {
            get {
                return ResourceManager.GetString("InstallationPathFrmHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the &apos;install&apos; button to start the installation. Once the application is installed, the user from the active directory will be synced to cloud. This synchronization will take place every 15 minutes..
        /// </summary>
        internal static string InstallDescription {
            get {
                return ResourceManager.GetString("InstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error has occured. Please fix the error and try again..
        /// </summary>
        internal static string InstallFailureMsg {
            get {
                return ResourceManager.GetString("InstallFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Sync Client Application.
        /// </summary>
        internal static string InstallHeading {
            get {
                return ResourceManager.GetString("InstallHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for installing sync client application. You active directory users belonging to group &apos;cloudidsyncusers&apos; will be synced with cloud every 15 minutes..
        /// </summary>
        internal static string InstallSuccessMsg {
            get {
                return ResourceManager.GetString("InstallSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string InstallWaitMessage {
            get {
                return ResourceManager.GetString("InstallWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer code / api key.
        /// </summary>
        internal static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Configuration.
        /// </summary>
        internal static string LDAPConfiguration {
            get {
                return ResourceManager.GetString("LDAPConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Path.
        /// </summary>
        internal static string LDAPPath {
            get {
                return ResourceManager.GetString("LDAPPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the LDAP path and the security group path in the textbox provided. This path will be used to fetch the user from the active directory group &apos;cloudidsyncusers&apos; and update into the cloud. If AD server is located at different location, please select the checkbox and provide the server name, server username and server password..
        /// </summary>
        internal static string LDAPPathDescription {
            get {
                return ResourceManager.GetString("LDAPPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter LDAP path.
        /// </summary>
        internal static string LDAPPathRequired {
            get {
                return ResourceManager.GetString("LDAPPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid LDAP path.
        /// </summary>
        internal static string LDAPPathValidation {
            get {
                return ResourceManager.GetString("LDAPPathValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU Path.
        /// </summary>
        internal static string LDAPSecurityGroup {
            get {
                return ResourceManager.GetString("LDAPSecurityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter OU path.
        /// </summary>
        internal static string LDAPSecurityGroupRequired {
            get {
                return ResourceManager.GetString("LDAPSecurityGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid OU path.
        /// </summary>
        internal static string LDAPSecurityGroupValidation {
            get {
                return ResourceManager.GetString("LDAPSecurityGroupValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty. Please enter a valid password.
        /// </summary>
        internal static string PasswordValidationMsg {
            get {
                return ResourceManager.GetString("PasswordValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path. Please enter a valid path..
        /// </summary>
        internal static string PathValidationMsg {
            get {
                return ResourceManager.GetString("PathValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Installation Path.
        /// </summary>
        internal static string SelectPath {
            get {
                return ResourceManager.GetString("SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be empty. If server name is not required, please de-select the checkbox above..
        /// </summary>
        internal static string ServerNameRequired {
            get {
                return ResourceManager.GetString("ServerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server password cannot be empty. Please provide a valid password..
        /// </summary>
        internal static string ServerPassweordRequired {
            get {
                return ResourceManager.GetString("ServerPassweordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server username cannot be empty. Please provide a valid username..
        /// </summary>
        internal static string ServerUserNameRequired {
            get {
                return ResourceManager.GetString("ServerUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Client application is used to sync the users from the active directory to the cloud. All the metadata which includes upn, SamsAccountName, FirstName, LastName, DisplayName, ObjectSid, EmailAddresses, AddressInformation, PhoneNumber, MobileNumber etc will be updated to cloud..
        /// </summary>
        internal static string StartFormDescription {
            get {
                return ResourceManager.GetString("StartFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Sync Client Application.
        /// </summary>
        internal static string StartFormHeading {
            get {
                return ResourceManager.GetString("StartFormHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync using.
        /// </summary>
        internal static string SyncOptionAvailability {
            get {
                return ResourceManager.GetString("SyncOptionAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like the users in AD to sync with cloud? The users in AD can be synced by two ways : by Email or by UPN. Please select the Syncing option..
        /// </summary>
        internal static string SyncOptionDescription {
            get {
                return ResourceManager.GetString("SyncOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing Option.
        /// </summary>
        internal static string SyncOptionHeading {
            get {
                return ResourceManager.GetString("SyncOptionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string UserDetail {
            get {
                return ResourceManager.GetString("UserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username and password in the below text box. This username and password will be validated against the api ..
        /// </summary>
        internal static string UserDetailsFrmDescription {
            get {
                return ResourceManager.GetString("UserDetailsFrmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username and Password.
        /// </summary>
        internal static string UserDetailsFrmHeading {
            get {
                return ResourceManager.GetString("UserDetailsFrmHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string UserDetailsFrmPassword {
            get {
                return ResourceManager.GetString("UserDetailsFrmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserDetailsFrmUserName {
            get {
                return ResourceManager.GetString("UserDetailsFrmUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty. Please enter a valid username.
        /// </summary>
        internal static string UsernameValidationMsg {
            get {
                return ResourceManager.GetString("UsernameValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
